const express = require('express')
// 创建路由对象
const router = express.Router()

const AdminHandle = require('../router_handle/adminApi')

router.post('/login', AdminHandle.login)
router.post('/getRoleRights', AdminHandle.getRoleRights)
router.get('/user', AdminHandle.user)
router.post('/changeRoleById', AdminHandle.changeRoleById)
router.post('/disabledUser', AdminHandle.disabledUser)
router.post('/addAdmin', AdminHandle.addAdmin)
router.get('/getNewsList', AdminHandle.getNewsList)
router.post('/deleteNewsByid', AdminHandle.deleteNewsByid)
router.post('/setHotNews', AdminHandle.setHotNews)
router.get('/getCategory', AdminHandle.getCategory)
router.post('/addNews', AdminHandle.addNews)
router.post('/getNewsById', AdminHandle.getNewsById)
router.get('/getVoluntLIst', AdminHandle.getVoluntLIst)
router.post('/deleteVoluntById', AdminHandle.deleteVoluntById)
router.post('/setHotVolunt', AdminHandle.setHotVolunt)
router.post('/setVoluntStatus', AdminHandle.setVoluntStatus)
router.post('/getVoluntById', AdminHandle.getVoluntById)
router.post('/addVolunt', AdminHandle.addVolunt)
router.get('/getVoluntUserList', AdminHandle.getVoluntUserList)
router.post('/deleteVoluntUserByUserid', AdminHandle.deleteVoluntUserByUserid)
router.post('/setUserIsvolunt', AdminHandle.setUserIsvolunt)
router.get('/getMessageList', AdminHandle.getMessageList)
router.post('/setUserMessage', AdminHandle.setUserMessage)
router.post('/deleteMessageById', AdminHandle.deleteMessageById)
router.get('/getLawdynamicList', AdminHandle.getLawdynamicList)
router.post('/deleteLawdynamicById', AdminHandle.deleteLawdynamicById)
router.post('/UpdateLawdynamic', AdminHandle.UpdateLawdynamic)
router.post('/AddLawdynamic', AdminHandle.AddLawdynamic)
router.get('/getServiceList', AdminHandle.getServiceList)
router.post('/addService', AdminHandle.addService)
router.post('/UpdateService', AdminHandle.UpdateService)
router.post('/deleteService', AdminHandle.deleteService)
router.get('/getServiceTabList', AdminHandle.getServiceTabList)
router.post('/deleteServiceTab', AdminHandle.deleteServiceTab)
router.post('/addTabname', AdminHandle.addTabname)
router.get('/getHospitalList', AdminHandle.getHospitalList)
router.post('/addHospital', AdminHandle.addHospital)
router.post('/UpdateHospital', AdminHandle.UpdateHospital)
router.post('/deleteHospital', AdminHandle.deleteHospital)
router.get('/getClinicRecord', AdminHandle.getClinicRecord)
router.post('/deleteClinicRecord', AdminHandle.deleteClinicRecord)
router.post('/updateClinicRecord', AdminHandle.updateClinicRecord)
router.get('/getClinic', AdminHandle.getClinic)
router.post('/updateClinic', AdminHandle.updateClinic)
router.post('/deleteClinic', AdminHandle.deleteClinic)
router.post('/addClinic', AdminHandle.addClinic)
router.get('/getHealthMsg', AdminHandle.getHealthMsg)
router.post('/setHealthMsgIsShow', AdminHandle.setHealthMsgIsShow)
router.post('/updateHealthMsg', AdminHandle.updateHealthMsg)
router.post('/addHealthMsg', AdminHandle.addHealthMsg)
router.post('/deleteHealthMsg', AdminHandle.deleteHealthMsg)
router.post('/getHealthMsgById', AdminHandle.getHealthMsgById)

// 将路由器 共享出去
module.exports = router